name: Rust

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          default: true
          override: true
    - name: Install cross-compilation tools
      uses: taiki-e/setup-cross-toolchain-action@v1
    - name: Build
      run: cargo build --release --verbose
    - uses: marvinpinto/action-automatic-releases@latest
      with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
              ./target/x86_64-unknown-linux-gnu/release/aisuclean
              ./target/aarch64-unknown-linux-gnu/release/aisuclean
#    - name: Run tests
#      run: cargo test --verbose
